
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_TYPE = 7;
  public static final int DIVIDE = 47;
  public static final int BOOL_TYPE = 3;
  public static final int POWER = 48;
  public static final int CHAR = 63;
  public static final int NOTEQUAL = 54;
  public static final int LPAREN = 29;
  public static final int INT = 62;
  public static final int MINUS = 45;
  public static final int FOR = 18;
  public static final int RAT_TYPE = 5;
  public static final int LESSTHANEQUAL = 51;
  public static final int RPAREN = 30;
  public static final int AND = 42;
  public static final int NOT = 41;
  public static final int SEMICOLON = 35;
  public static final int RANGE = 17;
  public static final int ILLEGAL_CHARACTER = 2;
  public static final int IN = 49;
  public static final int OR = 43;
  public static final int LESSTHAN = 38;
  public static final int TDEF = 21;
  public static final int COMMA = 39;
  public static final int STR_TYPE = 8;
  public static final int THREAD = 23;
  public static final int RAT = 61;
  public static final int MULTIPLY = 46;
  public static final int PLUS = 44;
  public static final int ASSIGN = 55;
  public static final int MAIN = 28;
  public static final int IF = 12;
  public static final int ID = 59;
  public static final int DOT = 40;
  public static final int WAIT = 24;
  public static final int OF = 19;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int EQUAL = 53;
  public static final int GREATTHAN = 37;
  public static final int TRUE = 57;
  public static final int error = 1;
  public static final int DICT_TYPE = 9;
  public static final int ANY_TYPE = 11;
  public static final int INT_TYPE = 4;
  public static final int GREATTHANEQUAL = 52;
  public static final int BREAK = 16;
  public static final int FDEF = 20;
  public static final int LBRACK = 31;
  public static final int COLON = 36;
  public static final int LBRACE = 33;
  public static final int ELSE = 14;
  public static final int READ = 25;
  public static final int RBRACK = 32;
  public static final int WHILE = 15;
  public static final int FLOAT = 60;
  public static final int SEQ_TYPE = 10;
  public static final int RBRACE = 34;
  public static final int STRING = 64;
  public static final int QUESTION = 56;
  public static final int ALIAS = 22;
  public static final int FALSE = 58;
  public static final int FLOAT_TYPE = 6;
  public static final int ELIF = 13;
  public static final int LENGTH = 50;
  public static final int PRINT = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ILLEGAL_CHARACTER",
  "BOOL_TYPE",
  "INT_TYPE",
  "RAT_TYPE",
  "FLOAT_TYPE",
  "CHAR_TYPE",
  "STR_TYPE",
  "DICT_TYPE",
  "SEQ_TYPE",
  "ANY_TYPE",
  "IF",
  "ELIF",
  "ELSE",
  "WHILE",
  "BREAK",
  "RANGE",
  "FOR",
  "OF",
  "FDEF",
  "TDEF",
  "ALIAS",
  "THREAD",
  "WAIT",
  "READ",
  "PRINT",
  "RETURN",
  "MAIN",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "COLON",
  "GREATTHAN",
  "LESSTHAN",
  "COMMA",
  "DOT",
  "NOT",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "POWER",
  "IN",
  "LENGTH",
  "LESSTHANEQUAL",
  "GREATTHANEQUAL",
  "EQUAL",
  "NOTEQUAL",
  "ASSIGN",
  "QUESTION",
  "TRUE",
  "FALSE",
  "ID",
  "FLOAT",
  "RAT",
  "INT",
  "CHAR",
  "STRING"
  };
}

